services:
  postgres:
    container_name: postgres
    image: postgres:17.5
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - /root/APi_griny/storage/postgres/data:/var/lib/postgresql/data
    restart: always
    networks:
      - api_griny

  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: always
    networks:
      - api_griny
  
  client:
    build:
      context: ../client
    container_name: client
    volumes:
      - client:/app
    networks:
      - api_griny
    env_file:
      - ../client/.env

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/letsencrypt
      - client:/client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - main
      - client
    restart: always
    networks:
      - api_griny

networks:
  api_griny:
    external: true